version: '2.27.0'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: production-management-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Originrega
    volumes:
      - ./db_scripts:/docker-entrypoint-initdb.d
    ports:
      - "7432:5432"
